title:               New Horizon
url:                 https://aoihanna.github.io
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Hanna
  url:               aoihanna.github.io
  email:             aoihanna@outlook.com

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
  - jekyll-compose